[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.32", features = ["full"] }
wtransport = "0.7.0"
rand = "0.8"
clap = { version = "4.4", features = ["derive"] }
