[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
core_affinity = "0.8.3"
io-uring = "0.7.11"
libc = "0.2.182"
quiche = "0.25.0"
rand = "0.8"
rcgen = "0.13.1"
rustc-hash = "2.1.1"
socket2 = "0.6.2"
zstd = "0.13.3"

[features]
debug-logs = []
